# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfEoZe0f_AmHMEU-JZkdzhBXGTH11l3D
"""




model = joblib.load("/content/linear_model.pkl")

age = st.number_input("Age", min_value=0, max_value=100, value=25)
sex = st.selectbox("Sex", ["M", "F"])
weight = st.number_input("Weight", min_value=30, max_value=200, value=150)
height = st.number_input("Height", min_value=100, max_value=250, value=170)
beauty = st.slider("Beauty on 10", 0, 10, 7)
skin_color = st.selectbox("Skin Color", ["black", "white", "yellow"])

sex_num = 0 if sex == "M" else 1
skin_black = 1 if skin_color == "black" else 0
skin_white = 1 if skin_color == "white" else 0
skin_yellow = 1 if skin_color == "yellow" else 0

input_df = pd.DataFrame({
    "age": [age],
    "sex": [sex_num],
    "weight": [weight],
    "height": [height],
    "beauty on 10": [beauty],
    "skin_black": [skin_black],
    "skin_white": [skin_white],
    "skin_yellow": [skin_yellow]
})

if st.button("Predict Price"):
    price_pred = model.predict(input_df)[0]
    st.success(f"Predicted Price: ${price_pred:.2f}")

